// (c) Copyright HutongGames, LLC 2010-2018. All rights reserved.
// THIS CONTENT IS AUTOMATICALLY GENERATED. __PLAYMAKER_EVENT_PROXY__
// this script was generated by the 'PlayMaker Event Proxy Wizard'. You can edit this script directly now, but prefer using the wizard if you are not sure.

using UnityEngine;
using HutongGames.PlayMaker.Ecosystem.Utils;

namespace com.yourdomain
{
	public class MyMessageProxy : PlayMakerEventProxy {

		[Button("MyMessage","Test : MyMessage")] public bool _;
		public void MyMessage()
		{
			if (debug || !Application.isPlaying)
			{
				Debug.Log("MyMessageProxy : MyMessage()");
			}
			base.SendPlayMakerEvent();
		}
	}
}